"use strict";
const $=id=>document.getElementById(id);
const base=location.pathname.replace(/\/$/,"");
function notice(message,error=false){$("notice").textContent=message;$("notice").style.display="block";$("notice").className=error?"error":"";}
async function api(route,data,method){const response=await fetch(base+route,{method:method||(data?"POST":"GET"),headers:{"Content-Type":"application/json","Authorization":"Bearer "+$("key").value.trim()},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||"请求失败");return result;}
function bind(id,fn){$(id).addEventListener("click",async()=>{const button=$(id);button.disabled=true;try{await fn();}catch(error){notice(error.message,true);}finally{button.disabled=false;}});}
bind("request",async()=>{await api("/v1/auth/request",{email:$("email").value.trim()});notice("验证码已进入发送队列，请检查邮箱；15 分钟内有效。");});
bind("verify",async()=>{const result=await api("/v1/auth/verify",{email:$("email").value.trim(),code:$("code").value.trim()});$("key").value=result.api_key;$("code").value="";notice("邮箱已验证。请安全保存账号密钥，再创建实验。");await refresh();});
bind("create",async()=>{const data={name:$("name").value.trim(),heartbeat_timeout:Number($("heartbeat").value),subject:$("subject").value,body:$("body").value};if($("runtime").value)data.runtime_timeout=Number($("runtime").value);if($("rules").value.trim())data.rules=JSON.parse($("rules").value);const result=await api("/v1/tasks",data);$("result").hidden=false;$("credentials").textContent="TASK_ID="+result.id+"\nTASK_KEY="+result.task_key;$("endpoint").textContent=location.origin+base+"/v1/tasks/"+result.id+"/events";notice("实验已创建。请开始上报心跳，避免触发失联提醒。");await refresh();});
async function refresh(){const result=await api("/v1/tasks");$("tasks").replaceChildren();for(const task of result.tasks){const row=document.createElement("div");row.className="task";const label=document.createElement("div");const name=document.createElement("strong");name.textContent=task.name;const status=document.createElement("span");status.textContent=task.status+" · "+new Date(task.created*1000).toLocaleString();label.append(name,status);const details=document.createElement("button");details.className="secondary";details.textContent="详情";details.onclick=async()=>{try{$("detail").textContent=JSON.stringify(await api("/v1/tasks/"+task.id),null,2);$("detail").hidden=false;}catch(e){notice(e.message,true);}};row.append(label,details);$("tasks").append(row);}if(!result.tasks.length)$("tasks").textContent="还没有实验。";}
bind("refresh",refresh);
fetch(base+"/health").then(r=>r.json()).then(h=>{$("health").textContent=h.ok?(h.mail_enabled?"服务在线 · 邮件已启用":"服务在线 · 邮件未启用"):"后台任务异常";if(!h.signup_enabled)notice("注册暂未开放。",true);}).catch(()=>{$("health").textContent="连接失败";});
