"use strict";
const $=id=>document.getElementById(id);
const route=location.pathname.match(/^(.*)\/dashboard\/([A-Za-z0-9_-]{43})$/);
const endpoint=route?route[1]+"/v1/dashboard/"+route[2]:null;
const labels={running:"运行中",waiting:"等待上报",outage:"心跳失联",succeeded:"已成功",failed:"已失败",cancelled:"已取消"};
const reasons={started:"开始",succeeded:"成功",failed:"失败",heartbeat_timeout:"中断",runtime_timeout:"超时"};
const mailStates={pending:"待发",sent:"已发送",dead:"发送失败",blocked:"已屏蔽",cancelled:"已取消"};
let snapshot=null,view="all",offset=0,query="",loading=false,revision=0,controller=null,searchTimer=null,detailId=null,detailLoading=false,lastUpdated=0,clockOffset=0;
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function now(){return Date.now()/1000+clockOffset;}
function duration(seconds){seconds=Math.max(0,Math.floor(seconds));if(seconds<60)return seconds+" 秒";if(seconds<3600)return Math.floor(seconds/60)+" 分 "+seconds%60+" 秒";if(seconds<86400)return Math.floor(seconds/3600)+" 时 "+Math.floor(seconds%3600/60)+" 分";return Math.floor(seconds/86400)+" 天 "+Math.floor(seconds%86400/3600)+" 时";}
function date(seconds){return new Date(seconds*1000).toLocaleString();}
function state(task){return task.outage?"outage":task.status==="running"&&!task.heartbeat_received?"waiting":task.status;}
function value(number){if(!Number.isFinite(number))return "—";return Number.isInteger(number)?String(number):Math.abs(number)<.0001&&number!==0?number.toExponential(2):Number(number.toPrecision(5)).toString();}
function connection(online){$("connection").className="live-status"+(online?"":" stale");$("live-text").textContent=online?"实时连接":"连接暂不可用";}
function showNotice(message=""){$("notice").textContent=message;}
async function getData(params,signal){const owned=signal?null:new AbortController();const timeout=owned?setTimeout(()=>owned.abort(),8000):null;try{const response=await fetch(endpoint+"?"+new URLSearchParams(params),{cache:"no-store",referrerPolicy:"no-referrer",signal:signal||owned.signal});if(!response.ok)throw new Error(response.status===404?"链接无效，请使用邮件中的完整链接。":response.status===429?"刷新频率达到限额，正在等待自动重试。":"连接暂不可用，显示的是上次更新结果。");return await response.json();}finally{if(timeout)clearTimeout(timeout);}}
function renderSummary(){const counts=snapshot.summary||{},total=Object.values(counts).reduce((a,b)=>a+b,0);$("summary").replaceChildren();for(const [label,count,note,cls] of [["全部",total,"未归档任务",""],["进行中",(counts.running||0)+(counts.waiting||0),(counts.waiting||0)+" 个等待首次上报","good"],["心跳失联",counts.outage||0,"需要关注","alert"],["已成功",counts.succeeded||0,"实验正常结束","good"],["已失败",counts.failed||0,"可查看详情或归档","alert"],["已归档",snapshot.archived_count||0,"已从总览中移除",""]]){const box=el("div",undefined,"stat "+cls),top=el("div",undefined,"stat-top");top.append(el("strong",String(count)),el("span",label));box.append(top,el("div",note,"stat-note"));$("summary").append(box);}}
function renderTabs(){const counts=snapshot?.summary||{},total=Object.values(counts).reduce((a,b)=>a+b,0);$("tabs").replaceChildren();for(const [key,label,count] of [["all","全部",total],["active","进行中",(counts.running||0)+(counts.waiting||0)],["outage","失联",counts.outage||0],["ended","已结束",(counts.succeeded||0)+(counts.failed||0)+(counts.cancelled||0)],["archived","已归档",snapshot?.archived_count||0]]){const button=el("button",undefined,"tab"+(view===key?" active":""));button.type="button";button.setAttribute("aria-pressed",String(view===key));button.append(el("span",label),el("span",String(count),"count"));button.onclick=()=>{view=key;offset=0;closeDetail();renderTabs();refresh(true);};$("tabs").append(button);}}
const collapsedGroups=new Set();
const groupOrder=new Intl.Collator("zh-CN",{numeric:true,sensitivity:"base"});
function taskGroups(tasks){const groups=new Map();for(const task of tasks){const title=task.name.trim().split(/[\s·|｜:：]+/u)[0]||"未命名任务",key=title.normalize("NFKC").toLocaleLowerCase();if(!groups.has(key))groups.set(key,{key,title,tasks:[]});groups.get(key).tasks.push(task);}return [...groups.values()].sort((a,b)=>groupOrder.compare(a.title,b.title)).map(group=>({...group,tasks:group.tasks.sort((a,b)=>a.created-b.created||a.id.localeCompare(b.id))}));}
function renderTable(){const tasks=snapshot.tasks;$("tasks").replaceChildren();$("empty").hidden=tasks.length>0;if(!tasks.length)$("empty").textContent=query?"没有匹配的实验。":"archived"===view?"还没有归档任务。结束后点击“归档”，它会收进这里。":"这个视图暂时没有任务。状态会自动更新，无需刷新。";
const groups=taskGroups(tasks);for(const group of groups){const header=el("tr",undefined,"group-row"),cell=el("td"),toggle=el("button",undefined,"group-toggle"),collapsed=collapsedGroups.has(group.key);cell.colSpan=7;header.dataset.groupKey=group.key;toggle.type="button";toggle.setAttribute("aria-expanded",String(!collapsed));toggle.title="按任务名称的项目前缀归组；组内按创建时间排列";toggle.append(el("span",collapsed?"▸":"▾","group-arrow"),el("strong",group.title),el("span",group.tasks.length+" 条记录","group-total"));const counts={};for(const task of group.tasks){const status=state(task);counts[status]=(counts[status]||0)+1;}for(const status of Object.keys(labels))if(counts[status])toggle.append(el("span",labels[status]+" "+counts[status],"group-status "+status));toggle.onclick=()=>{if(collapsedGroups.has(group.key))collapsedGroups.delete(group.key);else collapsedGroups.add(group.key);renderTable();};cell.append(toggle);header.append(cell);$("tasks").append(header);if(collapsed)continue;const names=new Map(),positions=new Map();for(const task of group.tasks)names.set(task.name,(names.get(task.name)||0)+1);
for(const task of group.tasks){const key=state(task),row=el("tr",undefined,key==="outage"?"outage-row":"");row.dataset.taskId=task.id;row.dataset.groupKey=group.key;
const title=el("td"),nameButton=el("button",undefined,"task-name");nameButton.type="button";nameButton.title=task.name+" · #"+task.id;nameButton.append(el("span",task.name,"name"),el("span","#"+task.id.slice(0,8),"short-id"));if(names.get(task.name)>1){const position=(positions.get(task.name)||0)+1;positions.set(task.name,position);nameButton.append(el("span","记录 "+position+"/"+names.get(task.name),"record-number"));}nameButton.onclick=()=>openDetail(task);title.append(nameButton);
const statusCell=el("td");statusCell.append(el("span",labels[key],"badge "+key));const heartbeat=el("td"),heartbeatText=task.heartbeat_received?duration(now()-task.heartbeat)+"前":"等待首次上报";heartbeat.title=task.heartbeat_received?"最后上报："+date(task.heartbeat)+"；失联阈值："+duration(task.heartbeat_timeout):"任务已创建，尚未收到第一个事件";heartbeat.append(el("span",heartbeatText,"heartbeat "+(task.outage?"lost":task.status==="running"?"fresh":"")));
const elapsed=el("td",duration((task.finished||now())-task.created),"duration-col runtime"),metrics=el("td",undefined,"metrics-col");let entries=Object.entries(task.metrics);entries.sort(([a],[b])=>a===task.trend_metric?-1:b===task.trend_metric?1:0);metrics.title=entries.map(([key,val])=>key+" = "+val).join(" · ");for(const [key,val] of entries.slice(0,2)){const item=el("span",undefined,"metric-inline");item.append(el("span",key),el("b",value(val)));metrics.append(item);}if(!entries.length)metrics.append(el("span","尚未上报","metric-missing"));
const mail=el("td",undefined,"mail-col"),notice=task.notifications[0];const mailText=notice?(reasons[notice.kind]||"指标")+" · "+(mailStates[notice.state]||notice.state):"—";mail.title=notice?date(notice.created)+"；已发送表示 SMTP 已接受，不保证进入收件箱":"暂无通知";mail.append(el("span",mailText,"mail-inline"+(notice?.state==="dead"?" error":"")));
const action=el("td");if(["succeeded","failed","cancelled"].includes(task.status)){const button=el("button",view==="archived"?"恢复":"归档","archive-button");button.title=view==="archived"?"恢复到总览":"从默认总览移除，可以恢复";button.type="button";button.onclick=()=>archive(task,button,view!=="archived");action.append(button);}row.append(title,statusCell,heartbeat,elapsed,metrics,mail,action);$("tasks").append(row);}}
$("result-count").textContent=tasks.length?"显示 "+(offset+1)+"–"+(offset+tasks.length)+" / "+snapshot.total+" 个任务 · 本页 "+groups.length+" 组":"0 个任务";$("previous").disabled=offset===0;$("next").disabled=!snapshot.has_more;$("page").textContent=(Math.floor(offset/200)+1)+" / "+Math.max(1,Math.ceil(snapshot.total/200));$("updated").textContent="最后更新 "+new Date(lastUpdated).toLocaleTimeString();}
async function refresh(force=false){if(!endpoint){showNotice("请打开邮件里的完整状态链接。");return;}if(loading&&!force)return;if(controller)controller.abort();controller=new AbortController();const current=++revision,abort=controller;loading=true;const timer=setTimeout(()=>abort.abort(),8000);
try{const data=await getData({offset,status:view==="archived"?"all":view,archived:view==="archived"?"1":"0",q:query,trends:"0"},abort.signal);if(current!==revision)return;snapshot=data;clockOffset=data.now-Date.now()/1000;lastUpdated=Date.now();if(offset>0&&!data.tasks.length){offset=Math.max(0,offset-200);loading=false;return refresh(true);}connection(true);showNotice(data.blocked?"此邮箱已屏蔽后续邮件，任务记录仍可查看和归档。":"");renderSummary();renderTabs();renderTable();if(detailId)refreshDetail();}catch(error){if(current!==revision)return;connection(false);showNotice(error.name==="AbortError"?"本次更新超时，保留上次结果，稍后自动重试。":error.message);}finally{clearTimeout(timer);if(current===revision)loading=false;}}
async function archive(task,button,archived){button.disabled=true;const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),8000);try{const response=await fetch(endpoint+"/archive",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_id:task.id,archived}),referrerPolicy:"no-referrer",signal:abort.signal});if(!response.ok){let message="整理失败，请稍后重试。";try{message=(await response.json()).error||message;}catch{}throw new Error(message);}if(detailId===task.id)closeDetail();await refresh(true);}catch(error){showNotice(error.message);}finally{clearTimeout(timeout);button.disabled=false;}}
function detailField(label,text){const field=el("div",undefined,"detail-field");field.append(el("span",label),el("strong",text));return field;}
function chart(task){const box=el("section",undefined,"chart");box.append(el("div",task.trend_metric?task.trend_metric+" · 指标趋势":"指标趋势","section-label"));if(task.trend.length<2){box.append(el("p","历史数据不足，至少需要两个采样点。","chart-caption"));return box;}const values=task.trend.map(p=>p.value),lo=Math.min(...values),hi=Math.max(...values),start=task.trend[0].time,end=task.trend.at(-1).time,svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 420 120");svg.setAttribute("role","img");svg.setAttribute("aria-label",task.trend_metric+" 趋势");for(const y of [20,60,100]){const line=document.createElementNS(svg.namespaceURI,"line");line.setAttribute("x1","0");line.setAttribute("x2","420");line.setAttribute("y1",String(y));line.setAttribute("y2",String(y));line.setAttribute("stroke","#edf1e7");svg.append(line);}const graph=document.createElementNS(svg.namespaceURI,"polyline");graph.setAttribute("points",task.trend.map(p=>[4+412*(p.time-start)/(end-start||1),hi===lo?60:108-96*(p.value-lo)/(hi-lo)].join(",")).join(" "));graph.setAttribute("fill","none");graph.setAttribute("stroke","#668656");graph.setAttribute("stroke-width","2");svg.append(graph);box.append(svg,el("div",date(start)+" → "+date(end)+" · "+task.trend.length+" 个采样点","chart-caption"));return box;}
function renderDetail(task){$("detail-name").textContent=task.name;const content=$("detail-content");content.replaceChildren(el("div","#"+task.id,"detail-id"));content.append(el("span",labels[state(task)],"badge "+state(task)));const meta=el("div",undefined,"detail-meta");meta.append(detailField("创建时间",date(task.created)),detailField("运行时长",duration((task.finished||now())-task.created)),detailField("最后上报",task.heartbeat_received?date(task.heartbeat):"等待首次上报"),detailField("失联阈值",task.heartbeat_enabled?duration(task.heartbeat_timeout):"未启用"));if(task.runtime_timeout)meta.append(detailField("运行时长上限",duration(task.runtime_timeout)));if(task.finished)meta.append(detailField("结束时间",date(task.finished)));content.append(meta);const metrics=el("div",undefined,"detail-metrics");for(const [key,val] of Object.entries(task.metrics)){const item=el("div",undefined,"detail-metric");item.append(el("span",key+" "),el("b",value(val)));metrics.append(item);}if(metrics.childElementCount)content.append(metrics);content.append(chart(task));const notices=el("section",undefined,"detail-notices");notices.append(el("div","通知记录","section-label"));for(const notice of task.notifications){const item=el("div",undefined,"notification");item.append(el("span",(reasons[notice.kind]||"指标达标")+" · "+(mailStates[notice.state]||notice.state)),el("span",date(notice.created)));notices.append(item);}content.append(notices);}
function openDetail(task){detailId=task.id;renderDetail({...task,trend:[]});if(!$("detail").open)$("detail").showModal();refreshDetail();}
function closeDetail(){detailId=null;if($("detail").open)$("detail").close();}
async function refreshDetail(){if(!detailId||detailLoading)return;const selected=detailId;detailLoading=true;try{const data=await getData({task:selected,archived:view==="archived"?"1":"0",trends:"1"});if(detailId!==selected)return;if(data.tasks[0])renderDetail(data.tasks[0]);else closeDetail();}catch{}finally{detailLoading=false;}}
$("search").oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{query=$("search").value.trim();offset=0;refresh(true);},250);};
$("previous").onclick=()=>{offset=Math.max(0,offset-200);refresh(true);};$("next").onclick=()=>{offset+=200;refresh(true);};$("close-detail").onclick=closeDetail;$("detail").onclose=()=>{detailId=null;};
document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh();});window.addEventListener("online",()=>refresh(true));window.addEventListener("offline",()=>{connection(false);showNotice("网络已断开，显示的是上次更新结果。恢复后自动重新连接。");});
renderTabs();refresh();setInterval(()=>{if(!document.hidden)refresh();},5000);
