"use strict";
const $=id=>document.getElementById(id);
const match=location.pathname.match(/^(.*)\/dashboard\/([A-Za-z0-9_-]{43})$/);
let snapshot=null,loading=false,offset=0;
const labels={running:"运行中",succeeded:"已成功",failed:"已失败",cancelled:"已取消",outage:"心跳失联"};
const reasons={started:"开始",succeeded:"成功",failed:"失败",heartbeat_timeout:"中断",runtime_timeout:"超时"};
const mailStates={pending:"待发",sent:"SMTP 已接受",dead:"发送失败",blocked:"已屏蔽",cancelled:"已取消"};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function duration(seconds){seconds=Math.max(0,Math.floor(seconds));if(seconds<60)return seconds+" 秒";if(seconds<3600)return Math.floor(seconds/60)+" 分钟";if(seconds<86400)return Math.floor(seconds/3600)+" 小时 "+Math.floor(seconds%3600/60)+" 分钟";return Math.floor(seconds/86400)+" 天 "+Math.floor(seconds%86400/3600)+" 小时";}
function date(seconds){return new Date(seconds*1000).toLocaleString();}
function trend(task){if(task.trend.length<2)return null;const box=el("div",undefined,"chart");box.append(el("p",task.trend_metric+" · 最近 "+task.trend.length+" 个采样点"));const values=task.trend.map(p=>p.value),lo=Math.min(...values),hi=Math.max(...values);const start=task.trend[0].time,end=task.trend.at(-1).time;const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 480 80");svg.setAttribute("role","img");svg.setAttribute("aria-label",task.trend_metric+" 指标趋势");const line=document.createElementNS(svg.namespaceURI,"polyline");line.setAttribute("points",task.trend.map(p=>[8+464*(p.time-start)/(end-start||1),hi===lo?40:70-60*(p.value-lo)/(hi-lo)].join(",")).join(" "));line.setAttribute("fill","none");line.setAttribute("stroke","#65854f");line.setAttribute("stroke-width","2.5");svg.append(line);box.append(svg,el("p",date(start)+" → "+date(end)));return box;}
function render(){if(!snapshot)return;const tasks=snapshot.tasks,now=snapshot.now;$("summary").replaceChildren();for(const [label,count] of [["已保留任务",snapshot.total],["本页运行中",tasks.filter(t=>t.status==="running"&&!t.outage).length],["本页失联",tasks.filter(t=>t.outage).length],["本页成功",tasks.filter(t=>t.status==="succeeded").length],["本页失败",tasks.filter(t=>t.status==="failed").length]]){const box=el("div",undefined,"stat");box.append(el("strong",String(count)),el("span",label));$("summary").append(box);}
$("previous").disabled=offset===0;$("next").disabled=!snapshot.has_more;$("page").textContent="第 "+(Math.floor(offset/200)+1)+" 页";
const query=$("search").value.trim().toLowerCase(),filter=$("filter").value;
const shown=tasks.filter(t=>(t.name.toLowerCase().includes(query)||t.id.includes(query))&&(filter==="all"||(filter==="outage"?t.outage:filter==="running"?t.status==="running"&&!t.outage:t.status===filter)));
$("tasks").replaceChildren();for(const task of shown){const card=el("article",undefined,"card"),state=task.outage?"outage":task.status,head=el("div",undefined,"card-head");head.append(el("h2",task.name),el("span",labels[state]||state,"badge "+state));card.append(head,el("p","#"+task.id,"id"));const meta=el("div",undefined,"meta");meta.append(el("span","创建 "+date(task.created)),el("span","已运行 "+duration((task.finished||now)-task.created)));card.append(meta);
const heartbeat=task.heartbeat_received?("最后上报 "+duration(now-task.heartbeat)+"前"):"等待首次上报";card.append(el("div",heartbeat+(task.heartbeat_enabled?" · 失联阈值 "+duration(task.heartbeat_timeout):" · 未启用失联提醒"),"meta"));
if(task.runtime_timeout){const age=(task.finished||now)-task.created,track=el("div",undefined,"track"),bar=el("progress");bar.max=task.runtime_timeout;bar.value=Math.min(task.runtime_timeout,Math.max(0,age));bar.setAttribute("aria-label","运行时长占设定上限的比例");track.append(bar);card.append(el("div","运行时长 / 上限 "+duration(task.runtime_timeout)+"（不是完成进度）","meta"),track);}
const metrics=el("div",undefined,"metrics");for(const [key,value] of Object.entries(task.metrics))metrics.append(el("span",key+" = "+value,"metric"));if(!metrics.childElementCount)metrics.append(el("span","尚未上报指标","empty-metric"));card.append(metrics);const graph=trend(task);if(graph)card.append(graph);
const notice=task.notifications[0];card.append(el("p",notice?("最近通知："+(reasons[notice.kind]||"指标达标")+" · "+(mailStates[notice.state]||notice.state)):"暂无通知","mail"));$("tasks").append(card);}
if(!shown.length)$("tasks").append(el("p","没有匹配的任务。新任务上报后会在这里更新。","empty"));$("updated").textContent="更新于 "+new Date().toLocaleTimeString()+" · 显示 "+shown.length+" / "+snapshot.total;}
async function refresh(){if(loading||!match)return;loading=true;$("refresh").disabled=true;try{const response=await fetch(match[1]+"/v1/dashboard/"+match[2]+"?offset="+offset,{cache:"no-store",referrerPolicy:"no-referrer"});if(!response.ok)throw new Error(response.status===404?"这个私有链接无效，请使用邮件里的完整链接。":response.status===429?"刷新频率过高，稍后自动重试。":"暂时无法更新，保留上次结果。");snapshot=await response.json();$("notice").className="";$("notice").textContent=snapshot.blocked?"此邮箱已屏蔽后续邮件，历史任务仍可查看。":"心跳正常时不会定期发邮件；任务开始和触发条件满足时才提醒。";render();}catch(e){$("notice").className="error";$("notice").textContent=e.message;}finally{loading=false;$("refresh").disabled=false;}}
$("previous").onclick=()=>{offset=Math.max(0,offset-200);refresh();};$("next").onclick=()=>{offset+=200;refresh();};
$("refresh").onclick=refresh;$("search").oninput=render;$("filter").onchange=render;
document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh();});
refresh();setInterval(()=>{if(!document.hidden)refresh();},15000);
